module.exports = {
  USER_STATUS: {
    BLOCKED: 'BLOCKED',
    DELETED: 'DELETED',
    IN_ACTIVE: 'IN_ACTIVE',
    ACTIVE: 'ACTIVE',
  },

  OTP_TYPE: {
    USER_REGISTRAION: 'USER_REGISTRAION',
    E_SIGNED_REQUESTED: 'E_SIGNED_REQUESTED',
    USER_EMAIL_REQUEST: 'USER_EMAIL_REQUEST',
  },

  USER_TYPE: {
    PLATFORM: 'PLATFORM',
    CUSTOMER: 'CUSTOMER',
  },
};
