module.exports = {
  USER_STATUS: {
    BLOCKED: 'BLOCKED',
    DELETED: 'DELETED',
    IN_ACTIVE: 'IN_ACTIVE',
    ACTIVE: 'ACTIVE',
  },

  OTP_TYPE: {
    USER_REGISTRAION: 'USER_REGISTRAION',
    E_SIGNED_REQUESTED: 'E_SIGNED_REQUESTED',
    USER_EMAIL_REQUEST: 'USER_EMAIL_REQUEST',
  },

  LOGIN_TYPE: {
    MOBILE_NUMBER_OTP: 'MOBILE_NUMBER_OTP',
    GOOGLE: 'GOOGLE',
    APPLE: 'APPLE',
    USER_NAME_PASSWORD: 'USER_NAME_PASSWORD',
    CLIENT_ID_SECRET: 'CLIENT_ID_SECRET',
  },

  USER_TYPE: {
    PLATFORM: 'PLATFORM',
    CUSTOMER: 'CUSTOMER',
  },

  CUSTOMER_IGNORE_PATH: [ '/api/register', '/api/verification', '/api/set-password', '/api/login' ],

  AUDIENCE_TYPE: {
    PLATFORM: 'PLATFORM',
    CUSTOMER: 'CUSTOMER',
  },

  ISSUER: 'AGILE WORLD TECHNOLOGIES',
};
